name: Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          path: ${{ github.workspace }}/nvim
